### ISSUE TITLE
Official Docker ROCm Pytorch images? Please support Python 3.x

### ISSUE THREAD

**Issue by kinred** [ROCmSoftwarePlatform/pytorch#444] opened 2019-07-31 14:28 UTC
Hi,
to me it is not clear where offical ROCm Pytorch docker images are hosted and which versions are currently available. I found this repo:

https://hub.docker.com/r/rocm/pytorch/tags

Is it the correct place?

If yes, it would be great if Python 3.x (or at least 3.6) would be supported in the latest images. Python 2 is already outdated for many code bases.

Thanks.

**Comment by iotamudelta** [comment] 2019-07-31 18:44
We are working w/ upstream to switch over to py3.6 for ROCm officially.

**Comment by briansp2020** [comment] 2019-07-31 20:04
@iotamudelta 
Can you give us ETA? I'm interested in running fast.ai and it requires Python 3.6. So far, I have not been able to make it run successfully. In fact, with the latest git checkout, I can't even get it to compile. :( I was able to at least compile and run with ROCM 2.5 or earlier version (https://github.com/ROCmSoftwarePlatform/pytorch/issues/427) even though it did not produce expected result.

**Comment by iotamudelta** [comment] 2019-07-31 20:09
@briansp2020 my PR to add the basic enablement landed. So you should be able to use just build. Let me give it a whirl myself. I'll report back.

**Comment by iotamudelta** [comment] 2019-07-31 22:24
please pull `rocm/pytorch:rocm2.5_ubuntu16.04_py3.6_pytorch` , I've just built this from upstream and confirmed that all unit tests pass on Radeon VII.

**Comment by briansp2020** [comment] 2019-08-01 00:32
@iotamudelta 
Your docker container seems to work. Do you have instructions on how to compile it on rocm 2.6 docker container?

Also, is ROCm team interested in supporting fastai? Fastai now seems to require nvidia-ml-py3. I'm guessing that not having equivalent library is one of the reason why fastai seems to run on CPU most of the time.

**Comment by saitam757** [comment] 2019-08-22 21:41
Hi, I also tried the repo [https://hub.docker.com/r/rocm/pytorch/tags](https://hub.docker.com/r/rocm/pytorch/tags) and pulled the container with the tag _rocm2.7_ubuntu16.04_py3.6_pytorch_ 
I got the error message _ImportError: No module named 'torch'_
Should that container suppose to work ? 
Thanks.

**Comment by iotamudelta** [comment] 2019-08-22 21:45
@saitam757 you need to use `python3.6` instead of `python` (which defaults to 2.7 in this docker).

**Comment by saitam757** [comment] 2019-08-23 16:59
@iotamudelta Thanks, seems to work. I started my python script yesterday with _python3_ but I have to explicitly use _python3.6_

**Comment by jithunnair-amd** [comment] 2019-08-23 18:24
@saitam757 Yes, the docker has python3.5 linked to "/usr/bin/python3" for whatever reason. If you change "/use/bin/python3" to point to python3.6 instead, then "python3" should also work as expected.

**Comment by iotamudelta** [comment] 2020-01-13 23:28
Closing this as all official docker images are using python 3.6 now. Note that `python3.6` must be invoked explicitly.

**Closed by iotamudelta** 2020-01-13 23:28 UTC
